default_language_version:
  python: python3.10
  node: 16.15.0
  ruby: 2.7.2

repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length, "120"]
        files: '^(openvino_xai|tests)/.*\.py'

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        files: '^(openvino_xai|tests)/.*\.py'
        additional_dependencies: [
            # numpy==1.19.5,
            types-PyYAML,
            attrs==21.2.*,
            types-requests,
            types-Deprecated,
            types-docutils,
            types_futures,
            types-python-dateutil,
            tokenize-rt==3.2.0,
          ]
        args: [--no-strict-optional, --ignore-missing-imports]

  # markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.yaml]

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.258"
    hooks:
      - id: ruff
        exclude: "tests"
        args: [--fix, --ignore, "E501"]
